### Create
POST {{host}}/api/users
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "123456"
}

### Read all
GET {{host}}/api/users

### Read by id
GET {{host}}/api/users/3

### Update by id
PUT {{host}}/api/users/4
Content-Type: application/json

{
  "name": "Carla Johnson",
  "email": "carlajohnson@example.com",
  "password": "01294857"
}

### Delete by id
DELETE {{host}}/api/users/3